CREATE SCHEMA IF NOT EXISTS discogs_api_integration;

USE discogs_api_integration;

CREATE TABLE artist (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    real_name VARCHAR(255),
    discogs_id BIGINT UNIQUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE album (
   id BIGINT AUTO_INCREMENT PRIMARY KEY,
   title VARCHAR(255) NOT NULL,
   year INT NOT NULL,
   discogs_release_id BIGINT UNIQUE,
   genres TEXT,
   styles TEXT,
   artist_id BIGINT NOT NULL,
   created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   CONSTRAINT fk_artist_album FOREIGN KEY (artist_id) REFERENCES artist(id) ON DELETE CASCADE
);
